// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwLX_bEz0WrXI5Hrg8kSumuU-5nNZOGsQ',
    appId: '1:515680236928:web:73847eecc2e01b4c98bd65',
    messagingSenderId: '515680236928',
    projectId: 'notes-manager-app-a8151',
    authDomain: 'notes-manager-app-a8151.firebaseapp.com',
    storageBucket: 'notes-manager-app-a8151.firebasestorage.app',
    measurementId: 'G-FPBWDJ25EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcWhSpEG9lzIafNKD4ycG9x_PX_L8iNX4',
    appId: '1:515680236928:android:81597b03e53f010698bd65',
    messagingSenderId: '515680236928',
    projectId: 'notes-manager-app-a8151',
    storageBucket: 'notes-manager-app-a8151.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxFXxqonlVxiSXH3A7kTK3TyQdf8Mm5i4',
    appId: '1:515680236928:ios:2c5b7faa59b15dfc98bd65',
    messagingSenderId: '515680236928',
    projectId: 'notes-manager-app-a8151',
    storageBucket: 'notes-manager-app-a8151.firebasestorage.app',
    iosBundleId: 'com.example.ipopiNotesVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxFXxqonlVxiSXH3A7kTK3TyQdf8Mm5i4',
    appId: '1:515680236928:ios:2c5b7faa59b15dfc98bd65',
    messagingSenderId: '515680236928',
    projectId: 'notes-manager-app-a8151',
    storageBucket: 'notes-manager-app-a8151.firebasestorage.app',
    iosBundleId: 'com.example.ipopiNotesVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwLX_bEz0WrXI5Hrg8kSumuU-5nNZOGsQ',
    appId: '1:515680236928:web:9295f503e14a873798bd65',
    messagingSenderId: '515680236928',
    projectId: 'notes-manager-app-a8151',
    authDomain: 'notes-manager-app-a8151.firebaseapp.com',
    storageBucket: 'notes-manager-app-a8151.firebasestorage.app',
    measurementId: 'G-KHT12VVL9B',
  );
}
